# ~/.config/starship.toml
#
# See https://starship.rs/config/ for explanation of the configuration options.

# PS2/PROMPT2
# 输入的命令为多行时的提示符
# continuation_prompt = "[∙∙∙](bright-black) "
continuation_prompt = "    "

[cmd_duration]
min_time = 0
show_milliseconds = true

[directory]
# disabled = true
# fish_style_pwd_dir_length = -1
fish_style_pwd_dir_length = 99
# truncation_length = 10
# truncate_to_repo = false

# show the current shell level $SHLVL
[shlvl]
disabled = false
format = "[$shlvl↕]($style) "
style = "yellow bold"

[status]
disabled = false
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
pipestatus = true

[time]
disabled = false
