# https://clangd.llvm.org/config

# https://clang.llvm.org/docs/ClangCommandLineReference.html
# https://gcc.gnu.org/onlinedocs/gcc/Option-Index.html

Diagnostics:
  ClangTidy:
    Remove:
      # 避免 Suspicious usage of 'sizeof(A*)'; pointer to aggregate
      - bugprone-sizeof-expression
  # 检查是否有不必要的 include
  UnusedIncludes: Strict
